### ISSUE TITLE
FAAS service for LogProxy

### ISSUE THREAD

**Issue by bimalkm191** [philips-labs/siderite#16]
Request for a FAAS service that will be easy for implementation for LogProxy

**Comment by bimalkm191** [comment]
Hello Andy.  When I see the logproxy implementation from https://github.com/philips-software/logproxy ,  we have to do below steps, which is a bunch of work for us. If you provide all these as FAAS, then we can eliminate many setup from our side. We will simply use the FAAS and integrate with our iron.io

- Configure logproxy
- Get the code docker pull philipssoftware/logproxy
- Create a new micro service using the keys and binding to log proxy service
- Do we need a rabitmq service also?
- Cf push the micro service which will enable iron.io logs to push to Kibana
- Need help how iron.io config will use the proxy service?

Please let me know I can setup a meeting with further discussion

**Comment by loafoe** [comment]
@bimalkm191 initial direct logging support is available in `v0.10` of siderite. Some testing is required and an example function will be povided

**Comment by loafoe** [comment]
This was implemented in `v0.11.0`, closing
