### ISSUE TITLE
doesn't install on windows

### ISSUE THREAD

**Issue by zdi** [philips-labs/siderite#24]
i tried installing on windows and got the following error:

```
$ go install
# github.com/philips-labs/siderite/cmd
cmd\function.go:63:9: undefined: syscall.Kill
cmd\function.go:70:9: undefined: syscall.Kill
cmd\function.go:79:9: undefined: syscall.Kill
cmd\function.go:84:8: undefined: syscall.Kill
```

**Comment by loafoe** [comment]
hi @zdi can you try and install the latest `main` commit on Windows?

**Comment by zdi** [comment]
the syscall problem seems to have been fixed 👍🏽 

however i ran into another problem, the build is interrupted by windows defender
`
$ go install
open C:\Users\320093~1\AppData\Local\Temp\go-build3424053970\b001\exe\a.out.exe: Operation did not complete successfully because the file contains a virus or potentially unwanted software.
`

looking at the windows security logs, it seems to be cause by the chisel library.
![image](https://user-images.githubusercontent.com/477078/128341256-4762a052-3189-43a8-ac90-0f26641c1077.png)


they are already aware of the problem, but don't have a fix yet [https://github.com/jpillora/chisel/issues/279](https://github.com/jpillora/chisel/issues/279)

**Comment by loafoe** [comment]
Argh, thanks for testing! I've just pushed a conditional build change which disabled the parts of the code that uses `chisel` on Windows. In reality this code is only used in task/function mode which is N/A on Windows. If you can try the latest change again, much appreciated.

**Comment by zdi** [comment]
thanks! that worked
